import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the CSV file generated by ncu
csv_file = "output_profile.csv"
df = pd.read_csv(csv_file)

# Check if required columns exist
required_columns = [
    "dram__bytes_read.sum", "dram__bytes_write.sum",
    "smsp__sass_thread_inst_executed_op_fadd_pred_on.sum",
    "smsp__sass_thread_inst_executed_op_fmul_pred_on.sum",
    "smsp__sass_thread_inst_executed_op_ffma_pred_on.sum",
    "sm__cycles_elapsed.avg"
]

for col in required_columns:
    if col not in df.columns:
        print(f"Warning: Column '{col}' not found in the CSV file. Using default value 0.")
        df[col] = 0  # Default to 0 if column is missing

# Extract relevant metrics
dram_read_bytes = df["dram__bytes_read.sum"]
dram_write_bytes = df["dram__bytes_write.sum"]
fadd = df["smsp__sass_thread_inst_executed_op_fadd_pred_on.sum"]
fmul = df["smsp__sass_thread_inst_executed_op_fmul_pred_on.sum"]
ffma = df["smsp__sass_thread_inst_executed_op_ffma_pred_on.sum"]
cycles_elapsed = df["sm__cycles_elapsed.avg"]

# Constants (replace with your GPU's peak values)
clock_freq = 1.41e9  # GPU clock frequency in Hz (e.g., 1.41 GHz for A100)
peak_compute = 19.5e12  # Peak FLOPS (e.g., 19.5 TFLOPS for A100 FP32)
peak_mem_bw = 1555e9  # Peak memory bandwidth in bytes/sec (e.g., 1555 GB/s for A100)

# Calculate total DRAM read/write bytes
total_dram_read = dram_read_bytes.sum()
total_dram_write = dram_write_bytes.sum()

# Calculate total FLOPs for each kernel
total_flops = fadd + fmul + 2 * ffma  # FFMA counts as 2 FLOPs

# Calculate arithmetic intensity for each kernel
arithmetic_intensity = total_flops / (dram_read_bytes + dram_write_bytes + 1e-9)  # Avoid division by zero

# Calculate performance (FLOPs/sec) for each kernel
time_sec = cycles_elapsed * (1 / clock_freq)  # Convert cycles to seconds
performance = total_flops / (time_sec + 1e-9)  # Avoid division by zero

# Print results
print("Total DRAM Read Bytes:", total_dram_read)
print("Total DRAM Write Bytes:", total_dram_write)
print("\nPer-Kernel Metrics:")
for i in range(len(df)):
    print(f"Kernel {i+1}:")
    print(f"  DRAM Read Bytes: {dram_read_bytes[i]}")
    print(f"  DRAM Write Bytes: {dram_write_bytes[i]}")
    print(f"  Total FLOPs: {total_flops[i]}")
    print(f"  Arithmetic Intensity: {arithmetic_intensity[i]} FLOPs/byte")
    print(f"  Performance: {performance[i]} FLOPs/sec")

# Generate Roofline Plot
ai = np.logspace(-1, 2, 100)  # Arithmetic intensity range
roofline = np.minimum(peak_compute, ai * peak_mem_bw)  # Roofline curve

plt.loglog(ai, roofline, 'k--', label='Roofline')
plt.scatter(arithmetic_intensity, performance, color='red', label='Kernels')
plt.xlabel('Arithmetic Intensity (FLOPs/byte)')
plt.ylabel('Performance (FLOPs/sec)')
plt.title('Roofline Plot')
plt.legend()
plt.grid(True)
plt.show()
